name = "Yuuki Sekai"
author = "Therdsak Chen"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e213a5e9087180f6b0b816e9a45e3aa4357f60be731b87c449e1505506490ea"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
