name = "Yuuki Sekai"
author = "Therdsak Chen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54f737945a159fa4a0e5f5bae10834e28ac9d3e85c93593c78962b283b2ed19e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
